# Generated by Django 6.0.6 on 2026-07-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0009_alter_product_seller_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
