# Generated by Django 6.0.6 on 2026-07-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0011_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
